name: Deploy to GitHub Pages

on:
  push:
    branches: [main]


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Dispatch event
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'custom-event',
              client_payload: {
                message: 'Hello World!'
              }
            })

      - uses: actions/checkout@v4

      - name: Clone external repository
        run: git clone https://github.com/thanejoss/MyBingWallpaper.git

      - name: Copy images to root
        run: cp -r MyBingWallpaper/images .

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      - uses: actions/deploy-pages@v3